version: "3.9"
services:
  arxiv-notifier:
    build: .
    restart: always
    environment:
      SLACK_BOT_TOKEN: "xoxb-your-real-token"
      SLACK_CHANNEL_ID: "C0XXXXXXX"
      POLL_INTERVAL: 3600  # 1 hour
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data  # seen.db 저장용
